export async function fetchingDataTFT({version, idioma, pais}){
    try {
        const urlDragon = `https://raw.communitydragon.org/${version}/cdragon/tft/${idioma}_${pais}.json`
        console.log(urlDragon)
        const fetching = await fetch(urlDragon, {cache:"reload"});
        const {items, sets} = await fetching.json();
        return {items, sets}
    } catch (error) {
        throw new Error('fetchingDataTFT');
    }
    
}

export const version = "latest";
export const idioma = "es"; //en
export const pais = "ar"; //mx /es /gb /us
export const set = "12";
const latestVersionLog = (await fetchingLatestVersionTFT()).version.split(".");
export const latestVersion = latestVersionLog[0]+"."+latestVersionLog[1];

export async function fetchingLatestVersionTFT(){
    const urlDragon = `https://raw.communitydragon.org/${version}/content-metadata.json`
    const fetching = await fetch(urlDragon, {cache:"reload"});
    return await fetching.json();
}


export const datosTFT = await fetchingDataTFT({version,idioma,pais});
export const championsTFT = await datosTFT.sets[set].champions;
export const itemsData = await datosTFT.items;

export const fetchMeta = await fetch(`https://guiadeparche.com/tftdata/Set${set}/metaTFTComposiciones.json`, {cache:"reload"});
export const meta = await fetchMeta.json();


export const augmentsIDList = [
    "TFT10_Augment_BigGains",
    "TFT10_Augment_CrashTestDummies",
    "TFT10_Augment_CrownGuarded",
    "TFT10_Augment_GoingLong",
    "TFT10_Augment_GoodForSomethingSilver",
    "TFT10_Augment_HelpIsOnTheWay",
    "TFT10_Augment_HeroicGrabBag",
    "TFT10_Augment_InspiringEpitaph",
    "TFT10_Augment_LearningToSpell",
    "TFT10_Augment_LittleBuddies",
    "TFT10_Augment_Scapegoat",
    "TFT10_Augment_SilverVeil",
    "TFT10_Augment_Stimpack",
    "TFT11_Augment_AtWhatCost",
    "TFT11_Augment_BloodBank",
    "TFT11_Augment_Buildabud",
    "TFT11_Augment_Calltochaos",
    "TFT11_Augment_DragonSpirit",
    "TFT11_Augment_Epoch",
    "TFT11_Augment_EpochPlus",
    "TFT11_Augment_FineVintage",
    "TFT11_Augment_GoldenRemover",
    "TFT11_Augment_OverEncumbered",
    "TFT11_Augment_Prizefighter",
    "TFT11_Augment_RadiantRefactor",
    "TFT11_Augment_RainingGold",
    "TFT11_Augment_RainingGoldPlus",
    "TFT11_Augment_Reinfourcement",
    "TFT11_Augment_ScoreboardScrapper",
    "TFT11_Augment_Slammin",
    "TFT11_Augment_Slammin_Plus",
    "TFT11_Augment_TinyButDeadly",
    "TFT11_Augment_WanderingTrainerGold",
    "TFT12_Augment_ArcanaCrest",
    "TFT12_Augment_ArcanaCrown",
    "TFT12_Augment_Bastion",
    "TFT12_Augment_BastionCrest",
    "TFT12_Augment_BastionCrown",
    "TFT12_Augment_BlasterCrest",
    "TFT12_Augment_BlasterCrown",
    "TFT12_Augment_BlitzcrankCarry",
    "TFT12_Augment_Chrono",
    "TFT12_Augment_ChronoCrest",
    "TFT12_Augment_ChronoCrown",
    "TFT12_Augment_Eldritch",
    "TFT12_Augment_EldritchCrest",
    "TFT12_Augment_EldritchCrown",
    "TFT12_Augment_EliseCarry",
    "TFT12_Augment_Faerie",
    "TFT12_Augment_FaerieCrest",
    "TFT12_Augment_FaerieCrown",
    "TFT12_Augment_Frost",
    "TFT12_Augment_FrostCrest",
    "TFT12_Augment_FrostCrown",
    "TFT12_Augment_GalioCarry",
    "TFT12_Augment_GalioCarryPlus",
    "TFT12_Augment_Honeymancy",
    "TFT12_Augment_HoneymancyCrest",
    "TFT12_Augment_HoneymancyCrown",
    "TFT12_Augment_Hunter",
    "TFT12_Augment_HunterCrest",
    "TFT12_Augment_HunterCrown",
    "TFT12_Augment_Incantor",
    "TFT12_Augment_IncantorCrest",
    "TFT12_Augment_IncantorCrown",
    "TFT12_Augment_LilliaCarry",
    "TFT12_Augment_Mage",
    "TFT12_Augment_MageCrest",
    "TFT12_Augment_MageCrown",
    "TFT12_Augment_Multistriker",
    "TFT12_Augment_MultistrikerCrest",
    "TFT12_Augment_MultistrikerCrown",
    "TFT12_Augment_NunuCarry",
    "TFT12_Augment_NunuCarryPlus",
    "TFT12_Augment_PoppyCarry",
    "TFT12_Augment_PortalCrest",
    "TFT12_Augment_PortalCrown",
    "TFT12_Augment_Preserver",
    "TFT12_Augment_PreserverCrest",
    "TFT12_Augment_PreserverCrown",
    "TFT12_Augment_Pyro",
    "TFT12_Augment_PyroCrest",
    "TFT12_Augment_PyroCrown",
    "TFT12_Augment_RumbleCarry",
    "TFT12_Augment_RumbleCarryPlus",
    "TFT12_Augment_Scholar",
    "TFT12_Augment_ScholarCrest",
    "TFT12_Augment_ScholarCrown",
    "TFT12_Augment_Shapeshifter",
    "TFT12_Augment_ShapeshifterCrest",
    "TFT12_Augment_ShapeshifterCrown",
    "TFT12_Augment_ShapeshifterPlus",
    "TFT12_Augment_Sugarcraft",
    "TFT12_Augment_SugarcraftCrest",
    "TFT12_Augment_SugarcraftCrown",
    "TFT12_Augment_Transfiguration",
    "TFT12_Augment_Vanguard",
    "TFT12_Augment_VanguardCrest",
    "TFT12_Augment_VanguardCrown",
    "TFT12_Augment_WarriorCrest",
    "TFT12_Augment_WarriorCrown",
    "TFT12_Augment_Witch",
    "TFT12_Augment_WitchcraftCrest",
    "TFT12_Augment_WitchcraftCrown",
    "TFT12_Augment_WukongCarry",
    "TFT6_Augment_ClearMind",
    "TFT6_Augment_Distancing",
    "TFT6_Augment_Diversify2",
    "TFT6_Augment_Featherweights1",
    "TFT6_Augment_ForceOfNature",
    "TFT6_Augment_GachaAddict",
    "TFT6_Augment_ItemGrabBag1",
    "TFT6_Augment_Keepers1",
    "TFT6_Augment_Keepers2",
    "TFT6_Augment_MaxLevel10",
    "TFT6_Augment_MetabolicAccelerator",
    "TFT6_Augment_OneTwoFive",
    "TFT6_Augment_PandorasItems",
    "TFT6_Augment_PortableForge",
    "TFT6_Augment_RadiantRelics",
    "TFT6_Augment_Recombobulator",
    "TFT6_Augment_SalvageBin",
    "TFT6_Augment_SlowAndSteady",
    "TFT6_Augment_TheGoldenEgg",
    "TFT6_Augment_ThreesCompany",
    "TFT6_Augment_TinyTitans",
    "TFT6_Augment_TradeSector",
    "TFT6_Augment_Traitless2",
    "TFT6_Augment_TriForce1",
    "TFT7_Augment_AFK",
    "TFT7_Augment_BandOfThieves1",
    "TFT7_Augment_BirthdayPresents",
    "TFT7_Augment_ClutteredMind",
    "TFT7_Augment_LategameSpecialist",
    "TFT7_Augment_LivingForge",
    "TFT7_Augment_LuckyGloves",
    "TFT7_Augment_LuckyGlovesPlus",
    "TFT7_Augment_PandorasBench",
    "TFT9_Augment_AllThatShimmers",
    "TFT9_Augment_ArmyBuilding",
    "TFT9_Augment_BalancedBudget2",
    "TFT9_Augment_BalancedBudgetPlus",
    "TFT9_Augment_BardPlaybook1",
    "TFT9_Augment_BardPlaybook2",
    "TFT9_Augment_BardPlaybook3",
    "TFT9_Augment_BigGrabBag",
    "TFT9_Augment_BlindingSpeed",
    "TFT9_Augment_BronzeTicket",
    "TFT9_Augment_BuildingACollectionPlusPlus",
    "TFT9_Augment_CapriciousForge",
    "TFT9_Augment_CombatCaster",
    "TFT9_Augment_Commander_Ascension",
    "TFT9_Augment_Commander_FinalAscension",
    "TFT9_Augment_Commander_PartialAscension",
    "TFT9_Augment_Commander_RollingForDays",
    "TFT9_Augment_Commander_TeamingUp1",
    "TFT9_Augment_Commander_TeamingUp2",
    "TFT9_Augment_CustomerIsAlwaysRight",
    "TFT9_Augment_DravenSpoilsOfWar",
    "TFT9_Augment_DravenSpoilsOfWar2",
    "TFT9_Augment_DravenSpoilsOfWar3",
    "TFT9_Augment_EscortQuest",
    "TFT9_Augment_Formation1",
    "TFT9_Augment_Formation2",
    "TFT9_Augment_HedgeFund",
    "TFT9_Augment_HighEndSector",
    "TFT9_Augment_ImpenetrableBulwark",
    "TFT9_Augment_IronAssets",
    "TFT9_Augment_LearningFromExperience2",
    "TFT9_Augment_LongDistanceRelationship2",
    "TFT9_Augment_LongTimeCrafting",
    "TFT9_Augment_Martyr",
    "TFT9_Augment_MissedConnections",
    "TFT9_Augment_NotToday",
    "TFT9_Augment_OldMansWalkingStick",
    "TFT9_Augment_OneTwosThree",
    "TFT9_Augment_PandorasItems2",
    "TFT9_Augment_PandorasRadiantBox",
    "TFT9_Augment_PhreakyFriday",
    "TFT9_Augment_PhreakyFridayPlus",
    "TFT9_Augment_PumpingUp",
    "TFT9_Augment_PumpingUp2",
    "TFT9_Augment_PumpingUp3",
    "TFT9_Augment_RedBuff",
    "TFT9_Augment_RiskyMoves",
    "TFT9_Augment_RollTheDice",
    "TFT9_Augment_SilverSpoon",
    "TFT9_Augment_Sleightofhand",
    "TFT9_Augment_StarsAreBorn",
    "TFT9_Augment_StationarySupport1",
    "TFT9_Augment_SupportCache",
    "TFT9_Augment_ThreesACrowd",
    "TFT9_Augment_TiniestTitan",
    "TFT9_Augment_TiniestTitanPlus",
    "TFT9_Augment_TwoHealthy",
    "TFT9_Augment_WanderingTrainer",
    "TFT9_Augment_WhatDoesntKillYou",
    "TFT9_Augment_WhatTheForge",
    "TFT9_Augment_YouHaveMyBow",
    "TFT9_Augment_YouHaveMySword",
    "TFT9_Augment_YoungAndWildAndFree",
    "TFT_Augment_AllThatShimmersPlus",
    "TFT_Augment_AnUpgradedJourney",
    "TFT_Augment_AssassinsToolbox",
    "TFT_Augment_AvengeTheFallen",
    "TFT_Augment_BeggarsCanBeChoosers",
    "TFT_Augment_BlossomingLotus1",
    "TFT_Augment_BlossomingLotus2",
    "TFT_Augment_BranchingOut",
    "TFT_Augment_CalledShot",
    "TFT_Augment_CategoryFive",
    "TFT_Augment_ClockworkAccelerator",
    "TFT_Augment_DarkAlleyDealings",
    "TFT_Augment_DawnbringersBlessing1",
    "TFT_Augment_DawnbringersBlessing2",
    "TFT_Augment_DoubleDown",
    "TFT_Augment_DualPurpose",
    "TFT_Augment_DuoQueue",
    "TFT_Augment_ExplosiveGrowth",
    "TFT_Augment_ExplosiveGrowthPlus",
    "TFT_Augment_FinalResistance",
    "TFT_Augment_FindYourCenter",
    "TFT_Augment_Flexible",
    "TFT_Augment_FortuneFavorsTheBold",
    "TFT_Augment_GiantAndMighty",
    "TFT_Augment_GoldenQuest",
    "TFT_Augment_HardCommit",
    "TFT_Augment_HighVoltage",
    "TFT_Augment_ImTheCarryNow",
    "TFT_Augment_InvestedPlus",
    "TFT_Augment_InvestedPlusPlus",
    "TFT_Augment_ItemCollector1",
    "TFT_Augment_ItemCollector2",
    "TFT_Augment_ItemLadder",
    "TFT_Augment_MarksmansToolbox",
    "TFT_Augment_Mentorship1",
    "TFT_Augment_Mentorship2",
    "TFT_Augment_OopsAllRageblades",
    "TFT_Augment_PatienceIsAVirtue",
    "TFT_Augment_PerfectLoss",
    "TFT_Augment_Pilfer",
    "TFT_Augment_Placebo",
    "TFT_Augment_PlaceboPlus",
    "TFT_Augment_RanduinsImmovableObject",
    "TFT_Augment_ReinforcedRejuvenation1",
    "TFT_Augment_ReinforcedRejuvenation2",
    "TFT_Augment_Replication",
    "TFT_Augment_RestartMission",
    "TFT_Augment_ShimmerscaleEssence",
    "TFT_Augment_Spellblades",
    "TFT_Augment_SpellcastersToolbox",
    "TFT_Augment_SubscriptionService",
    "TFT_Augment_SupportSentinel",
    "TFT_Augment_SupportSentinel2",
    "TFT_Augment_ThornPlatedArmor",
    "TFT_Augment_TraitTracker",
    "TFT_Augment_TwoTanky",
    "TFT_Augment_UnleashTheBeast",
    "TFT_Augment_UpwardMobility",
    "TFT_Augment_VerticallyInclined",
    "TFT_Augment_WorthTheWaitGold",
    "TFT_Augment_WorthTheWaitPrismatic"
]
