import {traitsColorsSet15} from "./traitsColorsSet15"
export const imgHex = ["hex-bronze.webp", "hex-silver.webp", "hex-gold.webp", "hex-prismatic.webp","hex-default.webp"]

export const traitsColors = {
    //Set 14
    TFT14_AnimaSquad:{
        3:imgHex[0],
        5:imgHex[1],
        7:imgHex[2],
        10:imgHex[3],
    },
    TFT14_Cyberboss:{
        2:imgHex[0],
        3:imgHex[1],
        4:imgHex[2],
    },
    TFT14_Divinicorp:{
        1:imgHex[0],
        3:imgHex[1],
        5:imgHex[2],
        7:imgHex[3],
    },
    TFT14_Netgod:{
        1:imgHex[3],
    },
    TFT14_StreetDemon:{
        3:imgHex[0],
        5:imgHex[1],
        7:imgHex[2],
        10:imgHex[3],
    },
    TFT14_Supercharge:{
        2:imgHex[0],
        3:imgHex[1],
        4:imgHex[1],
        5:imgHex[2],
    },
    TFT14_Vanguard:{
        2:imgHex[0],
        4:imgHex[1],
        6:imgHex[2],
    },
    TFT14_Strong:{
        2:imgHex[0],
        4:imgHex[1],
        6:imgHex[2],
    },
    TFT14_ViegoUniqueTrait:{
        1:imgHex[3],
    },
    TFT14_Cutter:{
        2:imgHex[0],
        3:imgHex[1],
        4:imgHex[1],
        5:imgHex[2],
    },
    TFT14_Armorclad:{
        2:imgHex[0],
        4:imgHex[1],
        6:imgHex[2],
    },
    TFT14_EdgeRunner:{
        3:imgHex[0],
        5:imgHex[1],
        7:imgHex[2],
        10:imgHex[3],
    },
    TFT14_Overlord:{
        1:imgHex[3],
    },
    TFT14_Swift:{
        2:imgHex[0],
        4:imgHex[1],
        6:imgHex[2],
        10:imgHex[3],
    },
    TFT14_Controller:{
        2:imgHex[0],
        3:imgHex[1],
        4:imgHex[1],
        5:imgHex[2],
    },
    TFT14_Bruiser:{
        2:imgHex[0],
        4:imgHex[1],
        6:imgHex[2],
    },
    TFT14_Marksman:{
        2:imgHex[0],
        4:imgHex[2],
    },
    TFT14_Immortal:{
        2:imgHex[0],
        4:imgHex[1],
        6:imgHex[2],
    },
    TFT14_BallisTek:{
        2:imgHex[0],
        4:imgHex[1],
        6:imgHex[2],
    },
    TFT14_Techie:{
        2:imgHex[0],
        4:imgHex[1],
        6:imgHex[2],
        8:imgHex[3],
    },
    TFT14_Thirsty:{
        2:imgHex[0],
        3:imgHex[1],
        4:imgHex[2],
    },
    TFT14_Virus:{
        1:imgHex[3],
    },
    TFT14_Mob:{
        3:imgHex[0],
        5:imgHex[1],
        7:imgHex[2],
    },
    TFT14_HotRod:{
        3:imgHex[0],
        5:imgHex[2],
    },
    TFT14_Suits:{
        3:imgHex[0],
        4:imgHex[1],
        5:imgHex[2],
    },
    //Set 15
    ...traitsColorsSet15


}

export const listaCampeones = [
    {
        nombre:"Ahri",
        img:"/campeones/set12/ahri.webp",
        coste:2,
        sinergia:["Arcana","Scholar"]
    },
    {
        nombre:"Akali",
        img:"/campeones/set12/akali.webp",
        coste:2,
        sinergia:["Pyro","Warrior", "Multistriker"]
    },
    {
        nombre:"Ashe",
        img:"/campeones/set12/ashe.webp",
        coste:1,
        sinergia:["Eldritch","Multistriker"]
    },
    {
        nombre:"Bard",
        img:"/campeones/set12/bard.webp",
        coste:3,
        sinergia:["Sugarcraft","Preserver","Scholar"]
    },
    {
        nombre:"Blitzcrank",
        img:"/campeones/set12/blitzcrank.webp",
        coste:1,
        sinergia:["Honeymancy","Vanguard"]
    },
    {
        nombre:"Briar",
        img:"/campeones/set12/briar.webp",
        coste:5,
        sinergia:["Ravenous","Eldritch","Shapeshifter"]
    },
    {
        nombre:"Camille",
        img:"/campeones/set12/camille.webp",
        coste:5,
        sinergia:["Chrono","Multistriker"]
    },
    {
        nombre:"Cassiopeia",
        img:"/campeones/set12/cassiopeia.webp",
        coste:2,
        sinergia:["Witchcraft","Incantor"]
    },
    {
        nombre:"Diana",
        img:"/campeones/set12/diana.webp",
        coste:5,
        sinergia:["Frost","Bastion"]
    },
    {
        nombre:"Elise",
        img:"/campeones/set12/elise.webp",
        coste:1,
        sinergia:["Eldritch","Shapeshifter"]
    },
    {
        nombre:"Ezreal",
        img:"/campeones/set12/ezreal.webp",
        coste:3,
        sinergia:["Portal","Blaster"]
    },
    {
        nombre:"Fiora",
        img:"/campeones/set12/fiora.webp",
        coste:4,
        sinergia:["Witchcraft","Warrior"]
    },
    {
        nombre:"Galio",
        img:"/campeones/set12/galio.webp",
        coste:2,
        sinergia:["Portal","Vanguard", "Mage"]
    },
    {
        nombre:"Gwen",
        img:"/campeones/set12/gwen.webp",
        coste:4,
        sinergia:["Sugarcraft","Warrior"]
    },
    {
        nombre:"Hecarim",
        img:"/campeones/set12/hecarim.webp",
        coste:3,
        sinergia:["Arcana","Bastion", "Multistriker"]
    },
    {
        nombre:"Hwei",
        img:"/campeones/set12/hwei.webp",
        coste:3,
        sinergia:["Frost","Blaster"]
    },
    {
        nombre:"Jax",
        img:"/campeones/set12/jax.webp",
        coste:1,
        sinergia:["Chrono","Multistriker"]
    },
    {
        nombre:"Jayce",
        img:"/campeones/set12/jayce.webp",
        coste:1,
        sinergia:["Portal","Shapeshifter"]
    },
    {
        nombre:"Jinx",
        img:"/campeones/set12/jinx.webp",
        coste:3,
        sinergia:["Sugarcraft","Hunter"]
    },
    {
        nombre:"Kalista",
        img:"/campeones/set12/kalista.webp",
        coste:4,
        sinergia:["Faerie","Multistriker"]
    },
    {
        nombre:"Karma",
        img:"/campeones/set12/karma.webp",
        coste:4,
        sinergia:["Chrono","Incantor"]
    },
    {
        nombre:"Kassadin",
        img:"/campeones/set12/kassadin.webp",
        coste:2,
        sinergia:["Portal","Multistriker"]
    },
    {
        nombre:"Katarina",
        img:"/campeones/set12/katarina.webp",
        coste:3,
        sinergia:["Faerie","Warrior"]
    },
    {
        nombre:"Kogmaw",
        img:"/campeones/set12/kogmaw.webp",
        coste:2,
        sinergia:["Honeymancy","Hunter"]
    },
    {
        nombre:"Lillia",
        img:"/campeones/set12/lillia.webp",
        coste:1,
        sinergia:["Faerie","Bastion"]
    },
    {
        nombre:"Milio",
        img:"/campeones/set12/milio.webp",
        coste:5,
        sinergia:["Faerie","Scholar"]
    },
    {
        nombre:"Mordekaiser",
        img:"/campeones/set12/mordekaiser.webp",
        coste:3,
        sinergia:["Eldritch","Vanguard"]
    },
    {
        nombre:"Morgana",
        img:"/campeones/set12/morgana.webp",
        coste:5,
        sinergia:["Witchcraft","BatQueen", "Preserver"]
    },
    {
        nombre:"Nami",
        img:"/campeones/set12/nami.webp",
        coste:4,
        sinergia:["Eldritch","Mage"]
    },
    {
        nombre:"Nasus",
        img:"/campeones/set12/nasus.webp",
        coste:4,
        sinergia:["Pyro","Shapeshifter"]
    },
    {
        nombre:"Neeko",
        img:"/campeones/set12/neeko.webp",
        coste:3,
        sinergia:["Witchcraft","Shapeshifter"]
    },
    {
        nombre:"Nilah",
        img:"/campeones/set12/nilah.webp",
        coste:2,
        sinergia:["Eldritch","Warrior"]
    },
    {
        nombre:"Nomsy",
        img:"/campeones/set12/nomsy.webp",
        coste:1,
        sinergia:["Dragon","Hunter"]
    },
    {
        nombre:"Norra",
        img:"/campeones/set12/norra.webp",
        coste:5,
        sinergia:["Portal","Best_Friends", "Mage"]
    },
    {
        nombre:"Nunu",
        img:"/campeones/set12/nunu.webp",
        coste:2,
        sinergia:["Honeymancy","Bastion"]
    },
    {
        nombre:"Olaf",
        img:"/campeones/set12/olaf.webp",
        coste:4,
        sinergia:["Frost","Hunter"]
    },
    {
        nombre:"Poppy",
        img:"/campeones/set12/poppy.webp",
        coste:1,
        sinergia:["Witchcraft","Bastion"]
    },
    {
        nombre:"Rakan",
        img:"/campeones/set12/rakan.webp",
        coste:4,
        sinergia:["Faerie","Preserver"]
    },
    {
        nombre:"Rumble",
        img:"/campeones/set12/rumble.webp",
        coste:2,
        sinergia:["Sugarcraft","Vanguard", "Blaster"]
    },
    {
        nombre:"Ryze",
        img:"/campeones/set12/ryze.webp",
        coste:4,
        sinergia:["Portal","Scholar"]
    },
    {
        nombre:"Seraphine",
        img:"/campeones/set12/seraphine.webp",
        coste:1,
        sinergia:["Faerie","Mage"]
    },
    {
        nombre:"Shen",
        img:"/campeones/set12/shen.webp",
        coste:3,
        sinergia:["Pyro","Bastion"]
    },
    {
        nombre:"Shyvana",
        img:"/campeones/set12/shyvana.webp",
        coste:2,
        sinergia:["Dragon","Shapeshifter"]
    },
    {
        nombre:"Smolder",
        img:"/campeones/set12/smolder.webp",
        coste:5,
        sinergia:["Dragon","Blaster"]
    },
    {
        nombre:"Soraka",
        img:"/campeones/set12/soraka.webp",
        coste:1,
        sinergia:["Sugarcraft","Mage"]
    },
    {
        nombre:"Swain",
        img:"/campeones/set12/swain.webp",
        coste:3,
        sinergia:["Frost","Shapeshifter"]
    },
    {
        nombre:"Syndra",
        img:"/campeones/set12/syndra.webp",
        coste:2,
        sinergia:["Eldritch","Incantor"]
    },
    {
        nombre:"Tahm Kench",
        img:"/campeones/set12/tahmkench.webp",
        coste:4,
        sinergia:["Arcana","Vanguard"]
    },
    {
        nombre:"Taric",
        img:"/campeones/set12/taric.webp",
        coste:4,
        sinergia:["Portal","Bastion"]
    },
    {
        nombre:"Tristana",
        img:"/campeones/set12/tristana.webp",
        coste:2,
        sinergia:["Faerie","Blaster"]
    },
    {
        nombre:"Twitch",
        img:"/campeones/set12/twitch.webp",
        coste:1,
        sinergia:["Frost","Hunter"]
    },
    {
        nombre:"Varus",
        img:"/campeones/set12/varus.webp",
        coste:4,
        sinergia:["Pyro","Blaster"]
    },
    {
        nombre:"Veigar",
        img:"/campeones/set12/veigar.webp",
        coste:3,
        sinergia:["Honeymancy","Mage"]
    },
    {
        nombre:"Vex",
        img:"/campeones/set12/vex.webp",
        coste:3,
        sinergia:["Chrono","Mage"]
    },
    {
        nombre:"Warwick",
        img:"/campeones/set12/warwick.webp",
        coste:1,
        sinergia:["Frost","Vanguard"]
    },
    {
        nombre:"Wukong",
        img:"/campeones/set12/wukong.webp",
        coste:3,
        sinergia:["Druid"]
    },
    {
        nombre:"Xerath",
        img:"/campeones/set12/xerath.webp",
        coste:5,
        sinergia:["Arcana","Ascendant"]
    },
    {
        nombre:"Ziggs",
        img:"/campeones/set12/ziggs.webp",
        coste:1,
        sinergia:["Honeymancy","Incantor"]
    },
    {
        nombre:"Zilean",
        img:"/campeones/set12/zilean.webp",
        coste:2,
        sinergia:["Frost","Chrono","Preserver"]
    },
    {
        nombre:"Zoe",
        img:"/campeones/set12/zoe.webp",
        coste:1,
        sinergia:["Portal","Witchcraft","Scholar"]
    },
]
