name: Deploy to GitHub Pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}
  API_KEY_GOOGLE: ${{ secrets.API_KEY_GOOGLE }}
  ID_CLIENTE_GOOGLE_API: ${{ secrets.ID_CLIENTE_GOOGLE_API }}
  TOKEN_META: ${{ secrets.TOKEN_META }}
  PUBLIC_TOKEN_META: ${{ secrets.PUBLIC_TOKEN_META }}
  SECRET_CLIENT_GOOGLE_CLOUD_OAUTH: ${{ secrets.SECRET_CLIENT_GOOGLE_CLOUD_OAUTH }}
  PUBLIC_ID_CLIENT_GOOGLE_CLOUD_OAUTH: ${{ secrets.PUBLIC_ID_CLIENT_GOOGLE_CLOUD_OAUTH }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      message:
        description: 'Mensaje del despliegue'
        required: false
        default: 'Actualización de composiciones'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
